language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
before_install:
  - chmod +x publish.sh
install: true
script: "./gradlew clean build"
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./publish.sh; fi
env:
  global:
  - CI_NAME=travis-ci
  - secure: "Kor77MWuy1BhEvjjs84F6bOksF9DVsFduIhcWYvFFivqoFL4GyL34KOFHjhQRZEl5sfjSNQO07qdKNzCNJLAWS6x9jJczBhkRdl2zaGSywRyMHFgwnvosajR8rSNvaCu61JC12Wpge8lA8+NbO9p887LufFG/dPWY1lKVINaC1LKqUW91draP51G03UGJnCCh1mjWSB39hOoHmkVvA+db6/99ow9hunDwCadGh1T7beQy/WFSrMN40iNBAGe/1Cc2bp8f8sCknCI9jzX9GRjA6BtTCip9ZstNvI9CSCrUHDKccNoi7sibsZM8RvacFV+uVbfb2pnCo58nnIylts2JEJ52TSDUj0sHRDonlCkO4ppAPETQr0BjHB+f9wWE7o7uDBcTVZNV2t1C0nix13XrKyj7W/5f5uEtqwblKtJQZynHnkJ1HVwlQ3gsQc+3SiGtmriAjFLO00YRyUb1WP3WS7mKyly7kwCHY6t5/iQhuqD7D7nXTHo9V2FAcS/5pW7Hov7XuHwj7N9STP6/wDgYPkERgQlCNVk2MFjp+Rgpq3s6P8DzgUjtAvKg5XyOQVYmdjA8+DiEnJ42VTKDNLV37/d6dlHlnS2OocpB9u7SmGC+Kc8lnX5pk1Yf4eReNz4V2AwXuRw/M275OwW9QGGAHCOoDCsafDNYtnGyi32INQ=" # bintray
  - secure: "kmGxa9Lozos4g4Y9OqPgxlz5OUJobtIlQjeTTun9RcB5FxUcyV/nxVSrc/yw00k2BwiD70DfB1Ajzwm6mYcpQYe/eTB5soiPfsFZhGDRhFzkvP5HOkvHbAUp0CgwvgaGAaLXg+lb3Lxrdc2tn0AajRMlkXVTGGxDfwFXJAS6rBF855s/h/VqFdlw/BmXwbf625vBhRTZ7YHQ2oQJGTafQpYMf0UdedLcn58RrqRBDE+tCiH/GqTjABc22rDI2uAzoZICkdnuOwedGaX4HzEkjrTD9dkhA16D3zojgPXqiQLT+AihGbVqVenC6Vws7Zy8KEAgYrTrINLDcu2c2C9mHud3q9bcdzBFDqk2nC11KffUxgCDu//NTayTBx6TleGuN3py5RAWTnTalHt/Nf282Dmfd50HSrD4DvDnMmDP8sZOMTENM4H4rit49J+MbDPP/6SLbfKm4c9HsrFjVd3mKfJh3UHLGCYU0DO7/YZUd9HV9pn8vdpsckWby37JoQ/cYwEJgdXzumd9OPYgwIGnLVqWZxQV1aiOK+1umFCiF32522OE0CjPhfDWNNBfKZMTquXEC+lVIhzWeS7LRXI/B299WjEdmNUIdbDz1eSLV0eu0d4Vc9hznRWdWdlRkk0O+DuQg2RR/t/BpnuKRkycqYSe9Wexkd+fnXulR1Lsh54=" # bintray